logging:
  level:
    ROOT: DEBUG
    tech.jhipster: DEBUG
    org.hibernate.SQL: DEBUG
    org.eclipse.jetty: INFO
    alfio: DEBUG
    alfio.controller.*: INFO
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){red} %clr(%-5p) %clr(${PID}){faint} %clr([%thread]){faint} %clr(%logger{36}){cyan} %clr(-){red} %clr(%msg){faint}%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p ${PID} [%thread] %logger{36} - %msg%n'
  logback:
    rollingpolicy:
      max-file-size: 30MB
      max-history: 0
  file:
    path: ./logs

spring:
  config:
    activate:
      on-profile: dev
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reservation?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: svuser
    password: survey2021!1
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    database: MYSQL
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
      hibernate.cache.hazelcast.instance_name: survey
      hibernate.cache.hazelcast.instance_port: 5881
      hibernate.cache.use_minimal_puts: true
      hibernate.cache.hazelcast.use_lite_member: true
  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
    contexts: dev, faker
  mail:
    host: email-smtp.ap-northeast-2.amazonaws.com
    port: 587
    username: AKIA4HNEY6KG22F3ES5T
    password: BMgV6+qRk8ntImrYQqPuDodi38I0C6l1kAtXcdbUPBP0
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: email-smtp.ap-northeast-2.amazonaws.com
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: true
  web:
    resources:
      cache:
        cachecontrol:
          cache-private: true
          must-revalidate: true
          max-age: 3600 # 1 hour
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: http://localhost:9080/auth/realms/survey
        registration:
          oidc:
            client-id: web_app
            client-secret: web_app
            scope: openid,profile,email
server:
  port: 8285
  forward-headers-strategy: native
  servlet:
    session:
      cookie:
        http-only: true
      timeout: 2h
  compression:
    enabled: true
  shutdown: graceful

